### ISSUE TITLE
python 2.6 support

### ISSUE THREAD

**Issue by kirienko** [kirienko/unseries#5]
Python ver. 2.6 is currently unsupported

**Comment by hugovk** [comment]
Unless you really need to use Python 2.6, I probably wouldn't bother:

* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by kirienko** [comment]
@hugovk I agree with you in general, but the point of this issue is full RHEL7 compatibility out of the box (they still use py-2.6).

**Comment by hugovk** [comment]
[DistroWatch.com](https://distrowatch.com/table.php?distribution=redhat) says RHEL 7 is Python 2.7.

**Comment by kirienko** [comment]
@hugovk  Well, you're right once again. In fact I use the Hortonworks [HDP 2.6](https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.0/bk_release-notes/content/download-links.html) image, and by default I have python 2.6 here, because this particular image is based on RHEL6. I haven't noticed it before.
